### ISSUE TITLE
go 版本 对于流量计算是否使用Vnstat每月自动清零？

### ISSUE THREAD

**Issue by wmjlxl** [cokemine/ServerStatus-goclient#1]
你好，

python 版本有个提示选择 “对于流量计算是否使用Vnstat每月自动清零？”
请问 go 版本也有这个功能么？
有的话怎么设置？
谢谢。

**Comment by cokemine** [comment]
Will add soon

**Comment by cokemine** [comment]
已经添加了,现在最新版本使用
`./status-client -dsn="username:password@yourip" -vnstat` 就可以使用 vnStat 了

**Comment by wmjlxl** [comment]
你好，我刚了一下加入 vnstat，
有几个 vps 都没问题。但有一个却是例外，提示如下：

2021/07/20 20:20:45 Connecting...
2021/07/20 20:20:45 Authentication successful. Access granted.

2021/07/20 20:20:45 You are connecting via: IPv4

2021/07/20 20:20:46 Please check if the installation of vnStat is correct

然后就自动关闭了

**Comment by cokemine** [comment]
@wmjlxl 运行一下`vnstat --oneline b`看看？

**Comment by wmjlxl** [comment]
当我运行的时候提示木有安装，现在安装就好了。再次感谢。

对了，问问这个 go 版本，加了 vnStat，就自动每月 1 日重新清零了？

**Comment by cokemine** [comment]
不一定是每月一号，如果使用的是之前的脚本的话，设定清零日期应该是自己可以设置的，默认是每月一号
