### ISSUE TITLE
试图在mac上装探针结果。。

### ISSUE THREAD

**Issue by Xielipton** [cokemine/ServerStatus-goclient#10]
2021/12/24 08:02:02 Connecting...
2021/12/24 08:02:02 Authentication required:

2021/12/24 08:02:03 Authentication successful. Access granted.

2021/12/24 08:02:03 You are connecting via: IPv4

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cokemine/ServerStatus-goclient/pkg/status.Cpu(0xc000016528, 0xc000194000)
	/home/runner/work/ServerStatus-goclient/ServerStatus-goclient/pkg/status/status.go:77 +0x129
main.connect()
	/home/runner/work/ServerStatus-goclient/ServerStatus-goclient/cmd/client/client.go:92 +0x5f1
main.main()
	/home/runner/work/ServerStatus-goclient/ServerStatus-goclient/cmd/client/client.go:160 +0x117

**Comment by cokemine** [comment]
Fixed in https://github.com/cokemine/ServerStatus-goclient/commit/85f05108c8db82a38d87c73d94328ebd3e650d58
