### ISSUE TITLE
可以提供一份alpine的amd64版本吗？

### ISSUE THREAD

**Issue by franocisgar** [cokemine/ServerStatus-goclient#27]
用脚本安装失败，听说alpine用了musl libc，所以go的程序很大部分会运行不了。
所以问下有哪位大佬可以帮忙编译一下？

**Comment by cokemine** [comment]
musl是静态编译进去的不会用不了的。看看运行日志吧

**Comment by franocisgar** [comment]
> musl是静态编译进去的不会用不了的。看看运行日志吧

localhost:~# bash status-client
status-client: status-client: cannot execute binary file
直接运行就报错了

**Comment by cokemine** [comment]
chmod +x status-client
./status-client

这样运行

**Comment by franocisgar** [comment]
> chmod +x status-client ./status-client
> 
> 这样运行

可以了，十分感谢！！
